import config from '@stoplight/scripts/rollup.config';

// We need to add commonjs support to import 'grammar.js' generated by PEG.js
import commonjs from 'rollup-plugin-commonjs';

config.plugins.push(commonjs())

export default config;
